using Unity.VisualScripting;
using UnityEngine;

public class EnemyShip : MonoBehaviour
{
    

    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
      
    }

    // Update is called once per frame
    void Update()
    {
        
    }
    private void OnCollisionEnter2D(Collision2D collision)
    {
        if (collision.gameObject.CompareTag("Bullet"))
        {
            Destroy(gameObject);
        }

        else if (collision.gameObject.CompareTag("Border"))
        {
            Destroy(gameObject);

        }
    }
}
